export const RESTAURANT_LIST_REQUEST = 'RESTAURANT_LIST_REQUEST'
export const RESTAURANT_LIST_SUCCESS = 'RESTAURANT_LIST_SUCCESS'
export const RESTAURANT_LIST_FAIL = 'RESTAURANT_LIST_FAIL'

export const RESTAURANT_DETAILS_REQUEST = 'RESTAURANT_DETAILS_REQUEST'
export const RESTAURANT_DETAILS_SUCCESS = 'RESTAURANT_DETAILS_SUCCESS'
export const RESTAURANT_DETAILS_FAIL = 'RESTAURANT_DETAILS_FAIL'

export const RESTAURANT_DELETE_REQUEST = 'RESTAURANT_DELETE_REQUEST'
export const RESTAURANT_DELETE_SUCCESS = 'RESTAURANT_DELETE_SUCCESS'
export const RESTAURANT_DELETE_FAIL = 'RESTAURANT_DELETE_FAIL'

export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST'
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS'
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL'

export const RESTAURANT_CREATE_REQUEST = 'RESTAURANT_CREATE_REQUEST'
export const RESTAURANT_CREATE_SUCCESS = 'RESTAURANT_CREATE_SUCCESS'
export const RESTAURANT_CREATE_FAIL = 'RESTAURANT_CREATE_FAIL'
export const RESTAURANT_CREATE_RESET = 'RESTAURANT_CREATE_RESET'

export const PRODUCT_CREATE_REQUEST = 'PRODUCT_CREATE_REQUEST'
export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS'
export const PRODUCT_CREATE_FAIL = 'PRODUCT_CREATE_FAIL'
export const PRODUCT_CREATE_RESET = 'PRODUCT_CREATE_RESET'

export const RESTAURANT_UPDATE_REQUEST = 'RESTAURANT_UPDATE_REQUEST'
export const RESTAURANT_UPDATE_SUCCESS = 'RESTAURANT_UPDATE_SUCCESS'
export const RESTAURANT_UPDATE_FAIL = 'RESTAURANT_UPDATE_FAIL'
export const RESTAURANT_UPDATE_RESET = 'RESTAURANT_UPDATE_RESET'

export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST'
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS'
export const PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL'
export const PRODUCT_UPDATE_RESET = 'PRODUCT_UPDATE_RESET'

export const RESTAURANT_CREATE_REVIEW_REQUEST = 'RESTAURANT_CREATE_REVIEW_REQUEST'
export const RESTAURANT_CREATE_REVIEW_SUCCESS = 'RESTAURANT_CREATE_REVIEW_SUCCESS'
export const RESTAURANT_CREATE_REVIEW_FAIL = 'RESTAURANT_CREATE_REVIEW_FAIL'
export const RESTAURANT_CREATE_REVIEW_RESET = 'RESTAURANT_CREATE_REVIEW_RESET'

export const RESTAURANT_TOP_REQUEST = 'RESTAURANT_TOP_REQUEST'
export const RESTAURANT_TOP_SUCCESS = 'RESTAURANT_TOP_SUCCESS'
export const RESTAURANT_TOP_FAIL = 'RESTAURANT_TOP_FAIL'

export const RESTAURANT_RECENTORDER_REQUEST = 'RESTAURANT_RECENTORDER_REQUEST'
export const RESTAURANT_RECENTORDER_SUCCESS = 'RESTAURANT_RECENTORDER_SUCCESS'
export const RESTAURANT_RECENTORDER_FAIL = 'RESTAURANT_RECENTORDER_FAIL'
